### ISSUE TITLE
Installation process is prune to malicious intentions.

### ISSUE THREAD

**Issue by Leref** [aoifb/aoi.fb#6]
I've noticed in your README,
You've stated you need to run a SH file based to remove aoi.js `classes` files and copy your "adjusted" package `classes` file to aoi.js.
 
First of all this, it's already sketchy as you are requiring users to use this, as this package could contain malware and eventually affect those who don't realize their Client/Bot have bloatware or their Tokens are being logged. 

I'm not saying you would do this or not, but this is already showing this package isn't made safely nor complete.

Also those who update aoi.js, it likely get override and cause failure on your package, which is the package issue.

Knowing that you need to make a script and allocate an other package for your package to work, already doesn't show promise of this package.

The modifications I've only checked briefly, are the Database related, if this an issue for your package,
Make an other Pull Request on aoi.js package.

**Comment by guihrib** [comment]
Pull request sent!

**Comment by USERSATOSHI** [comment]
a question regarding the sh file
why do u want to edit the original aoijs classes and use the customized one
that aoi.fb offers

i would like to know the reaons
and the changes that were made in the customized classes

**Comment by guihrib** [comment]
> a question regarding the sh file
> why do u want to edit the original aoijs classes and use the customized one
> that aoi.fb offers
> 
> i would like to know the reaons
> and the changes that were made in the customized classes

we make changes because anyway the database customization given aoi.js doesn't have the all function as an async function. I submitted an issue in which you replied saying that making the changes, but since it hasn't changed, and many are asking for updates from aoi.fb to work on aoi.jsV5 I had to do this, since you haven't had any changes yet to support changing the customdb's all function to an asynchronous function or accepting aoi.fb as a 'type', we had to take this temporary measure, I already spoke with leref and apologized for the methods, but I sent a PR to be given support to aoi.fb, as soon as they can analyze or even make the changes necessary, I will be grateful and thank you in advance for your attention to aoi.fb

**Comment by guihrib** [comment]
> a question regarding the sh file why do u want to edit the original aoijs classes and use the customized one that aoi.fb offers
> 
> i would like to know the reaons and the changes that were made in the customized classes

Pull-request : https://github.com/AkaruiDevelopment/aoi.js/pull/353

**Comment by guihrib** [comment]
> I've noticed in your README, You've stated you need to run a SH file based to remove aoi.js `classes` files and copy your "adjusted" package `classes` file to aoi.js.
> 
> First of all this, it's already sketchy as you are requiring users to use this, as this package could contain malware and eventually affect those who don't realize their Client/Bot have bloatware or their Tokens are being logged.
> 
> I'm not saying you would do this or not, but this is already showing this package isn't made safely nor complete.
> 
> Also those who update aoi.js, it likely get override and cause failure on your package, which is the package issue.
> 
> Knowing that you need to make a script and allocate an other package for your package to work, already doesn't show promise of this package.
> 
> The modifications I've only checked briefly, are the Database related, if this an issue for your package, Make an other Pull Request on aoi.js package.

Pull-request : https://github.com/AkaruiDevelopment/aoi.js/pull/353

**Comment by USERSATOSHI** [comment]
> > a question regarding the sh file
> > why do u want to edit the original aoijs classes and use the customized one
> > that aoi.fb offers
> > i would like to know the reaons
> > and the changes that were made in the customized classes
> 
> we make changes because anyway the database customization given aoi.js doesn't have the all function as an async function. I submitted an issue in which you replied saying that making the changes, but since it hasn't changed, and many are asking for updates from aoi.fb to work on aoi.jsV5 I had to do this, since you haven't had any changes yet to support changing the customdb's all function to an asynchronous function or accepting aoi.fb as a 'type', we had to take this temporary measure, I already spoke with leref and apologized for the methods, but I sent a PR to be given support to aoi.fb, as soon as they can analyze or even make the changes necessary, I will be grateful and thank you in advance for your attention to aoi.fb
> 
> Pull-request: [AkaruiDevelopment/aoi.js#353](https://github.com/AkaruiDevelopment/aoi.js/pull/353)

iirc
i did say that its in todo list
tho i am kinda busy which is delaying it
but it surely will be added
